a=[1,2,3]
msg = "Numers: {0} {1} {2}".format(a[0], a[1], a[2])
print(msg)
print("                                          ")
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
print("&".join(letters))
print("                                          ")
print("Hello C!".replace('C', 'Python'))
print("                                          ")
print('This is Python'.startswith('This'))
print("                                          ")
print('This is Python'.startswith('this'))
print("                                          ")
print('This is Python'.endswith('Python'))
print("                                          ")
print('this is me, YouXiu'.upper())
print("                                          ")
print('FEAR'.lower())
print("                                          ")
print("I, love, you!".split(","))
